Repository betagouv/signup.api.gouv.fr, pull requests merged in 2018-04, with the labels that each got.

#72 activation du fetch pour la home
  pages/index.js
  pages/tests/__snapshots__/index.test.js.snap
Labels: review

#74 reload page when login (quick and dirty fix)
  lib/user.js
Labels: review

#70 Us #45 afficher liste des demandes d un user connects to #45
  components/contractualisation-form.js
  components/enrollment.js
  components/tests/__snapshots__/contractualisation-form.test.js.snap
  components/tests/contractualisation-form.test.js
  lib/resource-provider.service.js
  lib/services.js
  lib/tests/resource-provider.service.test.js
  lib/tests/services.test.js
  mock/data/enrollments.json
  pages/demandes.js
  pages/tests/demandes.test.js
  static/styles/custom.css
Labels: review

#79 add correct link
  components/data-set-description.js
Labels: review

#77 Reformulation des textes d'info, suppression partie RGS
  components/contractualisation-form-fc.js
  components/contractualisation-form.js
  components/contractualisation-nav.js
  components/resource-provider.js
Labels: in progress

#84 Forcer le rafraichissement sous docker
  next.config.js
Labels: review

#86 Aggrandir les champs de réponse
  components/contractualisation-form-fc.js
Labels: next

#89 revisite du fonctionnement des entrants techniques
  components/contractualisation-form-fc.js
  components/contractualisation-nav.js
  components/enrollment.js
  components/entrants-techniques-form.js
  components/tests/__snapshots__/contractualisation-form.test.js.snap
  components/tests/__snapshots__/contractualisation-nav.test.js.snap
  components/tests/__snapshots__/resource-provider.test.js.snap
  lib/services.js
  next.config.js
  pages/contractualisation-fc.js
  pages/entrants-techniques.js
Labels: review

#117 Refonte formulaire API Particulier
  components/api-particulier-form.js
  components/page.js
  components/tests/__snapshots__/api-particulier-form.test.js.snap
  components/tests/__snapshots__/page.test.js.snap
  components/tests/__snapshots__/restricted-page.test.js.snap
  next.config.js
  pages/tests/__snapshots__/about.test.js.snap
  pages/tests/__snapshots__/api-particulier.test.js.snap
  pages/tests/__snapshots__/contact.test.js.snap
  pages/tests/__snapshots__/dgfip.test.js.snap
  static/styles/custom.css
Labels: review
