Repository betagouv/signup.api.gouv.fr, pull requests merged in 2018-03, with the labels that each got.

#28 Us #26 ajouter les jeux de donnees sur la home
  components/add-to-selection-button.js
  components/data-set-description.js
  components/data-set.js
  components/services.js
  components/tests/__snapshots__/Footer.test.js.snap
  components/tests/__snapshots__/add-to-selection-button.test.js.snap
  components/tests/__snapshots__/data-set-description.test.js.snap
  components/tests/__snapshots__/data-set.test.js.snap
  components/tests/__snapshots__/page.test.js.snap
  components/tests/__snapshots__/search.test.js.snap
  components/tests/__snapshots__/service.test.js.snap
  components/tests/__snapshots__/try-me-button.test.js.snap
  components/tests/add-to-selection-button.test.js
  components/tests/data-set-description.test.js
  components/tests/data-set.test.js
  components/tests/service.test.js
  components/tests/try-me-button.test.js
  components/try-me-button.js
  mock/data/caf.json
  mock/data/dgfip.json
  pages/index.js
Labels: review

#50 Dockerfile
  Dockerfile
Labels: review

#49 BSR corrige le login lors de l'appel du callback OAuth
  components/hoc/attach-user.js
  lib/user.js
Labels: review

#55 Us #20 ajout page contractualisation
  .env
  components/contractualisation-form.js
  components/contractualisation-nav.js
  components/header.js
  components/tests/__snapshots__/contractualisation-form.test.js.snap
  components/tests/__snapshots__/contractualisation-nav.test.js.snap
  components/tests/__snapshots__/header.test.js.snap
  components/tests/__snapshots__/page.test.js.snap
  components/tests/__snapshots__/restricted-page.test.js.snap
  components/tests/contractualisation-form.test.js
  components/tests/contractualisation-nav.test.js
  components/tests/hoc/attach-user.test.js
  lib/services.js
  lib/tests/services.test.js
  lib/tests/utils.test.js
  lib/utils.js
  mock/form/state.json
  next.config.js
  pages/contractualisation.js
  pages/tests/__snapshots__/about.test.js.snap
  pages/tests/__snapshots__/contact.test.js.snap
  pages/tests/__snapshots__/contractualisation.test.js.snap
  pages/tests/__snapshots__/demandes.test.js.snap
  pages/tests/__snapshots__/documentation.test.js.snap
  pages/tests/__snapshots__/index.test.js.snap
  pages/tests/contractualisation.test.js
  static/styles/custom.css
  yarn.lock
Labels: in progress

#63 Peut-être un correctif pour le login
  components/contractualisation-form.js
  components/hoc/attach-user.js
  components/hoc/with-user.js
  components/tests/__snapshots__/header.test.js.snap
  components/tests/header.test.js
  mock/form/state.json
Labels: review

#59 Utilise runkit pour les boutons "Essayez moi !"
  components/data-set-description.js
  components/tests/__snapshots__/data-set-description.test.js.snap
  components/tests/__snapshots__/link-button.test.js.snap
  components/tests/__snapshots__/resource-provider.test.js.snap
  components/tests/__snapshots__/try-me-button.test.js.snap
  components/try-me-button.js
  package.json
  static/styles/custom.css
  yarn.lock
Labels: freeze, in progress
